const box = document.createElement('div');
        box.style.width = '75px';
        box.style.height = '75px';
        box.style.backgroundColor = 'palevioletred';
        box.classList.add('box');
        container.appendChild(box);
const bo = document.createElement('div');
        bo.style.width = '75px';
        bo.style.height = '75px';
        bo.style.backgroundColor = 'palevioletred';
        box.classList.add('bo');
        container.appendChild(bo);
const b = document.createElement('div');
        b.style.width = '75px';
        b.style.height = '75px';
        b.style.backgroundColor = 'palevioletred';
        box.classList.add('b');
        container.appendChild(b);
const boxs = document.createElement('div');
        boxs.style.width = '75px';
        boxs.style.height = '75px';
        boxs.style.backgroundColor = 'palevioletred';
        box.classList.add('boxs');
        container.appendChild(boxs);